#!/bin/sh 
if [ -e ../libX11.a ]; then
exit 0
else

echo "* Compilando makekeys .."
cd src/util
gcc -DHAVE_CONFIG_H -I. -I. -I../../src    -Wall -Wpointer-arith -Wstrict-prototypes 	-Wmissing-prototypes -Wmissing-declarations 	-Wnested-externs -fno-strict-aliasing -I../../../headers -I../../../../X11/Xtrans   -I../../../headers -c makekeys.c
gcc  -g -O2   -o makekeys  makekeys.o  -ldl 
cd ..
echo "* Generando tablas .."
util/makekeys < ../../headers/X11/keysymdef.h > ks_tables_h
mv ks_tables_h ks_tables.h

cc()
{
echo Compilando $1 ..
gcc -w -DHAVE_CONFIG_H -I. -I. -I.    -include config.h -I../include -I../include/X11 -Wall -Wpointer-arith -Wstrict-prototypes -Wmissing-prototypes -Wmissing-declarations 	-Wnested-externs -fno-strict-aliasing -I../../headers -I../../headers/X11/Xtrans -DXTHREADS -DXUSE_MTSAFE_API  -DX11_DATADIR='"/usr/share/X11"' -g -c $1
}

cc AllCells.c
cc AllPlanes.c
cc AllowEv.c
cc AutoRep.c
cc Backgnd.c            
cc BdrWidth.c           
cc Bell.c 
cc Border.c  
cc ChAccCon.c  
cc ChActPGb.c
cc ChClMode.c  
cc ChCmap.c
cc ChGC.c 
cc ChKeyCon.c 
cc ChPntCon.c 
cc ChProp.c 
cc ChSaveSet.c  
cc ChWAttrs.c  
cc ChWindow.c  
cc ChkIfEv.c     
cc ChkMaskEv.c 
cc ChkTypEv.c  
cc ChkTypWEv.c 
cc ChkWinEv.c  
cc CirWin.c 
cc CirWinDn.c  
cc CirWinUp.c 
cc ClDisplay.c   
cc Clear.c
cc ClearArea.c  
cc ConfWind.c 
cc Context.c
cc ConvSel.c 
cc CopyArea.c   
cc CopyCmap.c   
cc CopyGC.c  
cc CopyPlane.c 
cc CrBFData.c 
cc CrCmap.c 
cc CrCursor.c 
cc CrGC.c  
cc CrGlCur.c 
cc CrPFBData.c 
cc CrPixmap.c  
cc CrWindow.c 
cc Cursor.c   
cc DefCursor.c  
cc DelProp.c  
cc Depths.c 
cc DestSubs.c  
cc DestWind.c   
cc DisName.c
cc DrArc.c  
cc DrArcs.c 
cc DrLine.c 
cc DrLines.c  
cc DrPoint.c 
cc DrPoints.c
cc DrRect.c
cc DrRects.c
cc DrSegs.c
cc ErrDes.c
cc ErrHndlr.c
cc EvToWire.c
cc FSSaver.c
cc FSWrap.c
cc FetchName.c
cc FillArc.c
cc FillArcs.c
cc FillPoly.c
cc FillRct.c
cc FillRcts.c
cc FilterEv.c
cc Flush.c
cc Font.c
cc FontInfo.c
cc FontNames.c
cc FreeCmap.c
cc FreeCols.c
cc FreeCurs.c
cc FreeEData.c
cc FreeGC.c
cc FreePix.c
cc GCMisc.c
cc Geom.c
cc GetAtomNm.c
cc GetColor.c
cc GetDflt.c
cc GetFPath.c
cc GetFProp.c
cc GetGCVals.c
cc GetGeom.c
cc GetHColor.c
cc GetHints.c
cc GetIFocus.c
cc GetImage.c
cc GetKCnt.c
cc GetMoEv.c
cc GetNrmHint.c
cc GetPCnt.c
cc GetPntMap.c
cc GetProp.c
cc GetRGBCMap.c
cc GetSOwner.c
cc GetSSaver.c
cc GetStCmap.c
cc GetTxtProp.c
cc GetWAttrs.c
cc GetWMCMapW.c
cc GetWMProto.c
cc GrButton.c
cc GrKey.c
cc GrKeybd.c
cc GrPointer.c
cc GrServer.c
cc Host.c
cc Iconify.c
cc IfEvent.c
cc ImText.c
cc ImText16.c
cc ImUtil.c
cc InitExt.c
cc InsCmap.c
cc IntAtom.c
cc KeyBind.c
cc KeysymStr.c
cc KillCl.c
cc LiHosts.c
cc LiICmaps.c
cc LiProps.c
cc ListExt.c
cc LoadFont.c
cc LockDis.c
cc LookupCol.c
cc LowerWin.c
cc Macros.c
cc MapRaised.c
cc MapSubs.c
cc MapWindow.c
cc MaskEvent.c
cc Misc.c
cc ModMap.c
cc MoveWin.c
cc NextEvent.c
cc OCWrap.c
cc OMWrap.c
cc OpenDis.c
cc ParseCmd.c
cc ParseCol.c
cc ParseGeom.c
cc PeekEvent.c
cc PeekIfEv.c
cc Pending.c
cc PixFormats.c
cc PmapBgnd.c
cc PmapBord.c
cc PolyReg.c
cc PolyTxt.c
cc PolyTxt16.c
cc PropAlloc.c
cc PutBEvent.c
cc PutImage.c
cc QuBest.c
cc QuColor.c
cc QuColors.c
cc QuCurShp.c
cc QuExt.c
cc QuKeybd.c
cc QuPntr.c
cc QuStipShp.c
cc QuTextE16.c
cc QuTextExt.c
cc QuTileShp.c
cc QuTree.c
cc Quarks.c
cc RaiseWin.c
cc RdBitF.c
cc RecolorC.c
cc ReconfWM.c
cc ReconfWin.c
cc Region.c
cc RegstFlt.c
cc RepWindow.c
cc RestackWs.c
cc RotProp.c
cc ScrResStr.c
cc SelInput.c
cc SendEvent.c
cc SetBack.c
cc SetCRects.c
cc SetClMask.c
cc SetClOrig.c
cc SetDashes.c
cc SetFPath.c
cc SetFont.c
cc SetFore.c
cc SetFunc.c
cc SetHints.c
cc SetIFocus.c
cc SetLStyle.c
cc SetLocale.c
cc SetNrmHint.c
cc SetPMask.c
cc SetPntMap.c
cc SetRGBCMap.c
cc SetSOwner.c
cc SetSSaver.c
cc SetStCmap.c
cc SetState.c
cc SetStip.c
cc SetTSOrig.c
cc SetTile.c
cc SetTxtProp.c
cc SetWMCMapW.c
cc SetWMProto.c
cc StBytes.c
cc StColor.c
cc StColors.c
cc StNColor.c
cc StName.c
cc StrKeysym.c
cc StrToText.c
cc Sync.c
cc Synchro.c
cc Text.c
cc Text16.c
cc TextExt.c
cc TextExt16.c
cc TextToStr.c
cc TrCoords.c
cc UndefCurs.c
cc UngrabBut.c
cc UngrabKbd.c
cc UngrabKey.c
cc UngrabPtr.c
cc UngrabSvr.c
cc UninsCmap.c
cc UnldFont.c
cc UnmapSubs.c
cc UnmapWin.c
cc VisUtil.c
cc WMGeom.c
cc WMProps.c
cc WarpPtr.c
cc WinEvent.c
cc Window.c
cc Withdraw.c
cc WrBitF.c
cc XlibAsync.c
cc XlibInt.c
cc Xrm.c
cc evtomask.c
cc globals.c
cc locking.c
cc x11_trans.c
cc ConnDis.c
cc xim_trans.c
cc ICWrap.c
cc IMWrap.c
cc XDefaultIMIF.c
cc XDefaultOMIF.c
cc XlcDL.c
cc XlcSL.c
cc imCallbk.c
cc imConv.c
cc imDefFlt.c
cc imDefIc.c
cc imDefIm.c
cc imDefLkup.c
cc imDispch.c
cc imEvToWire.c
cc imExten.c
cc imImSw.c
cc imInsClbk.c
cc imInt.c
cc imKStoUCS.c
cc imLcFlt.c
cc imLcGIc.c
cc imLcIc.c
cc imLcIm.c
cc imLcLkup.c
cc imLcPrs.c
cc imLcSIc.c
cc imRm.c
cc imRmAttr.c
cc imThaiFlt.c
cc imThaiIc.c
cc imThaiIm.c
cc imTrX.c
cc imTrans.c
cc imTransR.c
cc lcCT.c
cc lcCharSet.c
cc lcConv.c
cc lcDB.c
cc lcDefConv.c
cc lcDynamic.c
cc lcEuc.c
cc lcFile.c
cc lcGenConv.c
cc lcGeneric.c
cc lcInit.c
cc lcJis.c
cc lcPrTxt.c
cc lcPubWrap.c
cc lcPublic.c
cc lcRM.c
cc lcSjis.c
cc lcStd.c
cc lcTxtPr.c
cc lcUTF8.c
cc lcUTF8Load.c
cc lcUtil.c
cc lcWrap.c
cc mbWMProps.c
cc mbWrap.c
cc omDefault.c
cc omGeneric.c
cc omImText.c
cc omText.c
cc omTextEsc.c
cc omTextExt.c
cc omTextPer.c
cc omXChar.c
cc utf8WMProps.c
cc utf8Wrap.c
cc wcWrap.c
cc AddDIC.c
cc AddSF.c
cc CCC.c
cc CvColW.c
cc CvCols.c
cc HVC.c
cc HVCGcC.c
cc HVCGcV.c
cc HVCGcVC.c
cc HVCMnV.c
cc HVCMxC.c
cc HVCMxV.c
cc HVCMxVC.c
cc HVCMxVs.c
cc HVCWpAj.c
cc IdOfPr.c
cc LRGB.c
cc Lab.c
cc LabGcC.c
cc LabGcL.c
cc LabGcLC.c
cc LabMnL.c
cc LabMxC.c
cc LabMxL.c
cc LabMxLC.c
cc LabWpAj.c  
cc Luv.c  
cc LuvGcC.c  
cc LuvGcL.c  
cc LuvGcLC.c 
cc LuvMnL.c 
cc LuvMxC.c  
cc LuvMxL.c 
cc LuvMxLC.c 
cc LuvWpAj.c  
cc OfCCC.c  
cc PrOfId.c 
cc QBlack.c 
cc QBlue.c 
cc QGreen.c 
cc QRed.c 
cc QWhite.c  
cc QuCol.c 
cc QuCols.c
cc SetCCC.c 
cc SetGetCols.c  
cc StCol.c 
cc StCols.c  
cc UNDEFINED.c 
cc XRGB.c 
cc XYZ.c   
cc cmsAllCol.c  
cc cmsAllNCol.c  
cc cmsCmap.c
cc cmsColNm.c 
cc cmsGlobls.c  
cc cmsInt.c
cc cmsLkCol.c 
cc cmsMath.c
cc cmsProp.c
cc cmsTrig.c
cc uvY.c
cc xyY.c
cc XKB.c
cc XKBBind.c 
cc XKBCompat.c
cc XKBCtrls.c
cc XKBCvt.c  
cc XKBGetMap.c 
cc XKBGetByName.c 
cc XKBNames.c
cc XKBRdBuf.c
cc XKBSetMap.c 
cc XKBUse.c
cc XKBleds.c
cc XKBBell.c
cc XKBGeom.c
cc XKBSetGeom.c  
cc XKBExtDev.c 
cc XKBList.c 
cc XKBMisc.c
cc XKBMAlloc.c
cc XKBGAlloc.c 
cc XKBAlloc.c 

echo Generando libX11.a ..
ar cru ../../libX11.a  AllCells.o AllPlanes.o AllowEv.o AutoRep.o Backgnd.o BdrWidth.o Bell.o Border.o ChAccCon.o ChActPGb.o ChClMode.o ChCmap.o ChGC.o ChKeyCon.o ChPntCon.o ChProp.o ChSaveSet.o ChWAttrs.o ChWindow.o ChkIfEv.o ChkMaskEv.o ChkTypEv.o ChkTypWEv.o ChkWinEv.o CirWin.o CirWinDn.o CirWinUp.o ClDisplay.o Clear.o ClearArea.o ConfWind.o Context.o ConvSel.o CopyArea.o CopyCmap.o CopyGC.o CopyPlane.o CrBFData.o CrCmap.o CrCursor.o CrGC.o CrGlCur.o CrPFBData.o CrPixmap.o CrWindow.o Cursor.o DefCursor.o DelProp.o Depths.o DestSubs.o DestWind.o DisName.o DrArc.o DrArcs.o DrLine.o DrLines.o DrPoint.o DrPoints.o DrRect.o DrRects.o DrSegs.o ErrDes.o ErrHndlr.o EvToWire.o FSSaver.o FSWrap.o FetchName.o FillArc.o FillArcs.o FillPoly.o FillRct.o FillRcts.o FilterEv.o Flush.o Font.o FontInfo.o FontNames.o FreeCmap.o FreeCols.o FreeCurs.o FreeEData.o FreeGC.o FreePix.o GCMisc.o Geom.o GetAtomNm.o GetColor.o GetDflt.o GetFPath.o GetFProp.o GetGCVals.o GetGeom.o GetHColor.o GetHints.o GetIFocus.o GetImage.o GetKCnt.o GetMoEv.o GetNrmHint.o GetPCnt.o GetPntMap.o GetProp.o GetRGBCMap.o GetSOwner.o GetSSaver.o GetStCmap.o GetTxtProp.o GetWAttrs.o GetWMCMapW.o GetWMProto.o GrButton.o GrKey.o GrKeybd.o GrPointer.o GrServer.o Host.o Iconify.o IfEvent.o ImText.o ImText16.o ImUtil.o InitExt.o InsCmap.o IntAtom.o KeyBind.o KeysymStr.o KillCl.o LiHosts.o LiICmaps.o LiProps.o ListExt.o LoadFont.o LockDis.o LookupCol.o LowerWin.o Macros.o MapRaised.o MapSubs.o MapWindow.o MaskEvent.o Misc.o ModMap.o MoveWin.o NextEvent.o OCWrap.o OMWrap.o OpenDis.o ParseCmd.o ParseCol.o ParseGeom.o PeekEvent.o PeekIfEv.o Pending.o PixFormats.o PmapBgnd.o PmapBord.o PolyReg.o PolyTxt.o PolyTxt16.o PropAlloc.o PutBEvent.o PutImage.o QuBest.o QuColor.o QuColors.o QuCurShp.o QuExt.o QuKeybd.o QuPntr.o QuStipShp.o QuTextE16.o QuTextExt.o QuTileShp.o QuTree.o Quarks.o RaiseWin.o RdBitF.o RecolorC.o ReconfWM.o ReconfWin.o Region.o RegstFlt.o RepWindow.o RestackWs.o RotProp.o ScrResStr.o SelInput.o SendEvent.o SetBack.o SetCRects.o SetClMask.o SetClOrig.o SetDashes.o SetFPath.o SetFont.o SetFore.o SetFunc.o SetHints.o SetIFocus.o SetLStyle.o SetLocale.o SetNrmHint.o SetPMask.o SetPntMap.o SetRGBCMap.o SetSOwner.o SetSSaver.o SetStCmap.o SetState.o SetStip.o SetTSOrig.o SetTile.o SetTxtProp.o SetWMCMapW.o SetWMProto.o StBytes.o StColor.o StColors.o StNColor.o StName.o StrKeysym.o StrToText.o Sync.o Synchro.o Text.o Text16.o TextExt.o TextExt16.o TextToStr.o TrCoords.o UndefCurs.o UngrabBut.o UngrabKbd.o UngrabKey.o UngrabPtr.o UngrabSvr.o UninsCmap.o UnldFont.o UnmapSubs.o UnmapWin.o VisUtil.o WMGeom.o WMProps.o WarpPtr.o WinEvent.o Window.o Withdraw.o WrBitF.o XlibAsync.o XlibInt.o Xrm.o evtomask.o globals.o locking.o x11_trans.o ConnDis.o xim_trans.o ICWrap.o IMWrap.o XDefaultIMIF.o XDefaultOMIF.o XlcDL.o XlcSL.o imCallbk.o imConv.o imDefFlt.o imDefIc.o imDefIm.o imDefLkup.o imDispch.o imEvToWire.o imExten.o imImSw.o imInsClbk.o imInt.o imKStoUCS.o imLcFlt.o imLcGIc.o imLcIc.o imLcIm.o imLcLkup.o imLcPrs.o imLcSIc.o imRm.o imRmAttr.o imThaiFlt.o imThaiIc.o imThaiIm.o imTrX.o imTrans.o imTransR.o lcCT.o lcCharSet.o lcConv.o lcDB.o lcDefConv.o lcDynamic.o lcEuc.o lcFile.o lcGenConv.o lcGeneric.o lcInit.o lcJis.o lcPrTxt.o lcPubWrap.o lcPublic.o lcRM.o lcSjis.o lcStd.o lcTxtPr.o lcUTF8.o lcUTF8Load.o lcUtil.o lcWrap.o mbWMProps.o mbWrap.o omDefault.o omGeneric.o omImText.o omText.o omTextEsc.o omTextExt.o omTextPer.o omXChar.o utf8WMProps.o utf8Wrap.o wcWrap.o AddDIC.o AddSF.o CCC.o CvColW.o CvCols.o HVC.o HVCGcC.o HVCGcV.o HVCGcVC.o HVCMnV.o HVCMxC.o HVCMxV.o HVCMxVC.o HVCMxVs.o HVCWpAj.o IdOfPr.o LRGB.o Lab.o LabGcC.o LabGcL.o LabGcLC.o LabMnL.o LabMxC.o LabMxL.o LabMxLC.o LabWpAj.o Luv.o LuvGcC.o LuvGcL.o LuvGcLC.o LuvMnL.o LuvMxC.o LuvMxL.o LuvMxLC.o LuvWpAj.o OfCCC.o PrOfId.o QBlack.o QBlue.o QGreen.o QRed.o QWhite.o QuCol.o QuCols.o SetCCC.o SetGetCols.o StCol.o StCols.o UNDEFINED.o XRGB.o XYZ.o cmsAllCol.o cmsAllNCol.o cmsCmap.o cmsColNm.o cmsGlobls.o cmsInt.o cmsLkCol.o cmsMath.o cmsProp.o cmsTrig.o uvY.o xyY.o XKB.o XKBBind.o XKBCompat.o XKBCtrls.o XKBCvt.o XKBGetMap.o XKBGetByName.o XKBNames.o XKBRdBuf.o XKBSetMap.o XKBUse.o XKBleds.o XKBBell.o XKBGeom.o XKBSetGeom.o XKBExtDev.o XKBList.o XKBMisc.o XKBMAlloc.o XKBGAlloc.o XKBAlloc.o
ranlib ../../libX11.a
cd ..
fi

